### ISSUE TITLE
Add tests for dashboard creation

### ISSUE THREAD

**Issue by thomashopkins32** [nsls-ii-forge/nsls2forge-utils#15]
- Test with no feedstocks
- Test with one feedstock
- Test with different filename
- Test number of rows matches expected

**Comment by mrakitin** [comment]
Just to clarify, the first case ("Test with no feedstocks") should default to get the information for all feedstocks as it's the default behavior, right?

**Comment by thomashopkins32** [comment]
Yes but you can optionally provide a list of names instead of using the GitHub API. So having an empty list passed in is behavior we should test for.

**Comment by mrakitin** [comment]
Sounds good. Let's test this scenario as well.
